import { CommentaryItem, Match, NotificationItem, Player, Scorecard, TournamentStanding } from '../types/cricket';

export const mockMatches: Match[] = [
  {
    id: 'match_blr_mum_01',
    title: 'BLR vs MUM',
    seriesName: 'T20 Premier League 2025',
    matchNumber: '2nd Semi Final',
    venue: 'Wankhede Stadium',
    city: 'Mumbai',
    status: 'live',
    format: 'T20',
    currentInnings: 2,
    toss: 'Bengaluru Royals won the toss and elected to field',
    tossWinner: 'Bengaluru Royals',
    decision: 'bowl',
    team1: {
      id: 'team_mum',
      name: 'Mumbai Warriors',
      shortName: 'MUM',
      logo: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=128&q=80',
      score: 178,
      wickets: 4,
      overs: 20.0,
      maxOvers: 20,
    },
    team2: {
      id: 'team_blr',
      name: 'Bengaluru Royals',
      shortName: 'BLR',
      logo: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=128&q=80',
      score: 145,
      wickets: 3,
      overs: 18.2,
      maxOvers: 20,
    },
    battingTeamId: 'team_blr',
    bowlingTeamId: 'team_mum',
    target: 179,
    equation: 'Need 34 runs in 10 balls',
    crr: 7.91,
    rrr: 20.4,
    recentBalls: ['1', '2', '0', '4', 'W', '6', '1', '1'],
    activeBatters: {
      striker: {
        playerId: 'p_kohli',
        name: 'V. Kohli',
        shortName: 'V Kohli',
        runs: 68,
        balls: 42,
        fours: 6,
        sixes: 2,
        strikeRate: 161.9,
        isStriker: true,
        isNonStriker: false,
        isOut: false,
      },
      nonStriker: {
        playerId: 'p_maxwell',
        name: 'G. Maxwell',
        shortName: 'G Maxwell',
        runs: 24,
        balls: 11,
        fours: 2,
        sixes: 2,
        strikeRate: 218.2,
        isStriker: false,
        isNonStriker: true,
        isOut: false,
      },
    },
    activeBowler: {
      playerId: 'p_bumrah',
      name: 'J. Bumrah',
      shortName: 'J Bumrah',
      overs: 3.2,
      oversInBalls: 20,
      maidens: 0,
      runs: 28,
      wickets: 2,
      economy: 8.4,
      dots: 10,
      wides: 1,
      noBalls: 0,
      isCurrentBowler: true,
    },
    startTime: '2025-05-24T19:30:00Z',
    tournamentGroup: 'Playoffs',
  },
  {
    id: 'match_che_del_02',
    title: 'CHE vs DEL',
    seriesName: 'Indian Challenge Cup',
    matchNumber: 'Match 41',
    venue: 'M. A. Chidambaram Stadium',
    city: 'Chennai',
    status: 'live',
    format: 'T20',
    currentInnings: 1,
    toss: 'Chennai Kings won toss & elected to bat',
    tossWinner: 'Chennai Kings',
    decision: 'bat',
    team1: {
      id: 'team_che',
      name: 'Chennai Kings',
      shortName: 'CHE',
      logo: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=128&q=80',
      score: 112,
      wickets: 2,
      overs: 13.4,
      maxOvers: 20,
    },
    team2: {
      id: 'team_del',
      name: 'Delhi Strikers',
      shortName: 'DEL',
      logo: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=128&q=80',
      score: 0,
      wickets: 0,
      overs: 0,
      maxOvers: 20,
    },
    battingTeamId: 'team_che',
    bowlingTeamId: 'team_del',
    crr: 8.19,
    recentBalls: ['1', '0', '4', '1', '1', '2'],
    activeBatters: {
      striker: {
        playerId: 'p_gaikwad',
        name: 'R. Gaikwad',
        shortName: 'R Gaikwad',
        runs: 54,
        balls: 38,
        fours: 5,
        sixes: 2,
        strikeRate: 142.1,
        isStriker: true,
        isNonStriker: false,
        isOut: false,
      },
      nonStriker: {
        playerId: 'p_dube',
        name: 'S. Dube',
        shortName: 'S Dube',
        runs: 28,
        balls: 16,
        fours: 1,
        sixes: 3,
        strikeRate: 175.0,
        isStriker: false,
        isNonStriker: true,
        isOut: false,
      },
    },
    activeBowler: {
      playerId: 'p_kuldeep',
      name: 'K. Yadav',
      shortName: 'K Yadav',
      overs: 2.4,
      oversInBalls: 16,
      maidens: 0,
      runs: 19,
      wickets: 1,
      economy: 7.12,
      dots: 6,
      wides: 0,
      noBalls: 0,
      isCurrentBowler: true,
    },
    startTime: '2025-05-24T15:30:00Z',
    tournamentGroup: 'Group A',
  },
  {
    id: 'match_kol_hyd_03',
    title: 'KOL vs HYD',
    seriesName: 'T20 Premier League 2025',
    matchNumber: 'Grand Final',
    venue: 'Eden Gardens',
    city: 'Kolkata',
    status: 'upcoming',
    format: 'T20',
    currentInnings: 1,
    toss: 'Toss at 19:00 IST',
    tossWinner: '',
    decision: 'bat',
    team1: {
      id: 'team_kol',
      name: 'Kolkata Knights',
      shortName: 'KOL',
      logo: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=128&q=80',
      score: 0,
      wickets: 0,
      overs: 0,
      maxOvers: 20,
    },
    team2: {
      id: 'team_hyd',
      name: 'Hyderabad Sunbirds',
      shortName: 'HYD',
      logo: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=128&q=80',
      score: 0,
      wickets: 0,
      overs: 0,
      maxOvers: 20,
    },
    battingTeamId: 'team_kol',
    bowlingTeamId: 'team_hyd',
    crr: 0,
    recentBalls: [],
    activeBatters: {
      striker: {
        playerId: 'p_narine',
        name: 'S. Narine',
        shortName: 'S Narine',
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        isStriker: true,
        isNonStriker: false,
        isOut: false,
      },
      nonStriker: {
        playerId: 'p_iyer',
        name: 'S. Iyer',
        shortName: 'S Iyer',
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        isStriker: false,
        isNonStriker: true,
        isOut: false,
      },
    },
    activeBowler: {
      playerId: 'p_cummins',
      name: 'P. Cummins',
      shortName: 'P Cummins',
      overs: 0,
      oversInBalls: 0,
      maidens: 0,
      runs: 0,
      wickets: 0,
      economy: 0,
      dots: 0,
      wides: 0,
      noBalls: 0,
      isCurrentBowler: true,
    },
    startTime: '2025-05-26T19:30:00Z',
    tournamentGroup: 'Playoffs',
  },
  {
    id: 'match_mum_kol_04',
    title: 'MUM vs KOL',
    seriesName: 'T20 Premier League 2025',
    matchNumber: '1st Semi Final',
    venue: 'Narendra Modi Stadium',
    city: 'Ahmedabad',
    status: 'completed',
    format: 'T20',
    currentInnings: 2,
    toss: 'Kolkata Knights won toss & elected to bat',
    tossWinner: 'Kolkata Knights',
    decision: 'bat',
    team1: {
      id: 'team_kol',
      name: 'Kolkata Knights',
      shortName: 'KOL',
      logo: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=128&q=80',
      score: 194,
      wickets: 5,
      overs: 20.0,
      maxOvers: 20,
    },
    team2: {
      id: 'team_mum',
      name: 'Mumbai Warriors',
      shortName: 'MUM',
      logo: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=128&q=80',
      score: 168,
      wickets: 8,
      overs: 20.0,
      maxOvers: 20,
    },
    battingTeamId: 'team_mum',
    bowlingTeamId: 'team_kol',
    target: 195,
    equation: 'Kolkata Knights won by 26 runs',
    result: 'Kolkata Knights won by 26 runs',
    crr: 8.4,
    recentBalls: ['1', '0', 'W', '4', '1', '1'],
    activeBatters: {
      striker: {
        playerId: 'p_rohit',
        name: 'R. Sharma',
        shortName: 'R Sharma',
        runs: 52,
        balls: 31,
        fours: 5,
        sixes: 3,
        strikeRate: 167.7,
        isStriker: false,
        isNonStriker: false,
        isOut: true,
      },
      nonStriker: {
        playerId: 'p_sky',
        name: 'S. Yadav',
        shortName: 'S Yadav',
        runs: 41,
        balls: 23,
        fours: 4,
        sixes: 2,
        strikeRate: 178.2,
        isStriker: false,
        isNonStriker: false,
        isOut: true,
      },
    },
    activeBowler: {
      playerId: 'p_starc',
      name: 'M. Starc',
      shortName: 'M Starc',
      overs: 4.0,
      oversInBalls: 24,
      maidens: 0,
      runs: 34,
      wickets: 3,
      economy: 8.5,
      dots: 11,
      wides: 2,
      noBalls: 0,
      isCurrentBowler: false,
    },
    startTime: '2025-05-22T19:30:00Z',
    tournamentGroup: 'Playoffs',
  },
];

export const mockScorecards: Record<string, Scorecard> = {
  match_blr_mum_01: {
    matchId: 'match_blr_mum_01',
    innings1: {
      teamId: 'team_mum',
      teamName: 'Mumbai Warriors',
      shortName: 'MUM',
      score: 178,
      wickets: 4,
      overs: 20.0,
      legalBalls: 120,
      maxOvers: 20,
      runRate: 8.9,
      batting: [
        {
          playerId: 'p_rohit',
          name: 'Rohit Sharma',
          shortName: 'R Sharma',
          runs: 45,
          balls: 28,
          fours: 5,
          sixes: 2,
          strikeRate: 160.7,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'c Maxwell b Siraj',
        },
        {
          playerId: 'p_ishan',
          name: 'Ishan Kishan (wk)',
          shortName: 'I Kishan',
          runs: 32,
          balls: 22,
          fours: 4,
          sixes: 1,
          strikeRate: 145.5,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'b Dayal',
        },
        {
          playerId: 'p_sky',
          name: 'Suryakumar Yadav',
          shortName: 'S Yadav',
          runs: 62,
          balls: 35,
          fours: 6,
          sixes: 4,
          strikeRate: 177.1,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'c Kohli b Ferguson',
        },
        {
          playerId: 'p_tilak',
          name: 'Tilak Varma',
          shortName: 'T Varma',
          runs: 24,
          balls: 19,
          fours: 2,
          sixes: 1,
          strikeRate: 126.3,
          isStriker: false,
          isNonStriker: false,
          isOut: false,
        },
        {
          playerId: 'p_hardik',
          name: 'Hardik Pandya (c)',
          shortName: 'H Pandya',
          runs: 11,
          balls: 6,
          fours: 1,
          sixes: 1,
          strikeRate: 183.3,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'run out (Kohli)',
        },
      ],
      bowling: [
        {
          playerId: 'p_siraj',
          name: 'Mohammed Siraj',
          shortName: 'M Siraj',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 38,
          wickets: 1,
          economy: 9.5,
          dots: 8,
          wides: 2,
          noBalls: 0,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_dayal',
          name: 'Yash Dayal',
          shortName: 'Y Dayal',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 32,
          wickets: 1,
          economy: 8.0,
          dots: 9,
          wides: 1,
          noBalls: 0,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_ferguson',
          name: 'Lockie Ferguson',
          shortName: 'L Ferguson',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 41,
          wickets: 1,
          economy: 10.25,
          dots: 6,
          wides: 3,
          noBalls: 1,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_maxwell',
          name: 'Glenn Maxwell',
          shortName: 'G Maxwell',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 28,
          wickets: 0,
          economy: 7.0,
          dots: 10,
          wides: 0,
          noBalls: 0,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_swapnil',
          name: 'Swapnil Singh',
          shortName: 'S Singh',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 35,
          wickets: 0,
          economy: 8.75,
          dots: 7,
          wides: 1,
          noBalls: 0,
          isCurrentBowler: false,
        },
      ],
      extras: { wides: 7, noBalls: 1, byes: 0, legByes: 2, penalty: 0, total: 10 },
      fallOfWickets: [
        { wicketNumber: 1, score: 58, over: 6.2, playerName: 'Rohit Sharma' },
        { wicketNumber: 2, score: 94, over: 10.5, playerName: 'Ishan Kishan' },
        { wicketNumber: 3, score: 162, over: 18.1, playerName: 'Suryakumar Yadav' },
        { wicketNumber: 4, score: 178, over: 19.6, playerName: 'Hardik Pandya' },
      ],
    },
    innings2: {
      teamId: 'team_blr',
      teamName: 'Bengaluru Royals',
      shortName: 'BLR',
      score: 145,
      wickets: 3,
      overs: 18.2,
      legalBalls: 110,
      maxOvers: 20,
      runRate: 7.91,
      batting: [
        {
          playerId: 'p_kohli',
          name: 'Virat Kohli (c)*',
          shortName: 'V Kohli',
          runs: 68,
          balls: 42,
          fours: 6,
          sixes: 2,
          strikeRate: 161.9,
          isStriker: true,
          isNonStriker: false,
          isOut: false,
        },
        {
          playerId: 'p_faf',
          name: 'Faf du Plessis',
          shortName: 'F du Plessis',
          runs: 34,
          balls: 22,
          fours: 4,
          sixes: 1,
          strikeRate: 154.5,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'c Rohit b Bumrah',
        },
        {
          playerId: 'p_patidar',
          name: 'Rajat Patidar',
          shortName: 'R Patidar',
          runs: 16,
          balls: 12,
          fours: 2,
          sixes: 0,
          strikeRate: 133.3,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'b Chawla',
        },
        {
          playerId: 'p_green',
          name: 'Cameron Green',
          shortName: 'C Green',
          runs: 3,
          balls: 5,
          fours: 0,
          sixes: 0,
          strikeRate: 60.0,
          isStriker: false,
          isNonStriker: false,
          isOut: true,
          dismissalInfo: 'lbw b Bumrah',
        },
        {
          playerId: 'p_maxwell',
          name: 'Glenn Maxwell',
          shortName: 'G Maxwell',
          runs: 24,
          balls: 11,
          fours: 2,
          sixes: 2,
          strikeRate: 218.2,
          isStriker: false,
          isNonStriker: true,
          isOut: false,
        },
      ],
      bowling: [
        {
          playerId: 'p_bumrah',
          name: 'Jasprit Bumrah',
          shortName: 'J Bumrah',
          overs: 3.2,
          oversInBalls: 20,
          maidens: 0,
          runs: 28,
          wickets: 2,
          economy: 8.4,
          dots: 10,
          wides: 1,
          noBalls: 0,
          isCurrentBowler: true,
        },
        {
          playerId: 'p_coetzee',
          name: 'Gerald Coetzee',
          shortName: 'G Coetzee',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 42,
          wickets: 0,
          economy: 10.5,
          dots: 5,
          wides: 2,
          noBalls: 1,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_hardik',
          name: 'Hardik Pandya',
          shortName: 'H Pandya',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 35,
          wickets: 0,
          economy: 8.75,
          dots: 7,
          wides: 0,
          noBalls: 0,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_chawla',
          name: 'Piyush Chawla',
          shortName: 'P Chawla',
          overs: 4.0,
          oversInBalls: 24,
          maidens: 0,
          runs: 26,
          wickets: 1,
          economy: 6.5,
          dots: 11,
          wides: 0,
          noBalls: 0,
          isCurrentBowler: false,
        },
        {
          playerId: 'p_madhwal',
          name: 'Akash Madhwal',
          shortName: 'A Madhwal',
          overs: 3.0,
          oversInBalls: 18,
          maidens: 0,
          runs: 30,
          wickets: 0,
          economy: 10.0,
          dots: 4,
          wides: 1,
          noBalls: 0,
          isCurrentBowler: false,
        },
      ],
      extras: { wides: 4, noBalls: 1, byes: 0, legByes: 3, penalty: 0, total: 8 },
      fallOfWickets: [
        { wicketNumber: 1, score: 62, over: 7.1, playerName: 'Faf du Plessis' },
        { wicketNumber: 2, score: 98, over: 12.3, playerName: 'Rajat Patidar' },
        { wicketNumber: 3, score: 115, over: 15.2, playerName: 'Cameron Green' },
      ],
    },
  },
};

export const mockCommentaryFeed: CommentaryItem[] = [
  {
    id: 'c_18_2',
    matchId: 'match_blr_mum_01',
    over: '18.2',
    bowlerName: 'J Bumrah',
    strikerName: 'G Maxwell',
    runs: 1,
    ballType: 'run',
    isBoundary: false,
    isWicket: false,
    title: '1 run',
    description: 'Yorker on middle stump! Dug out safely to deep mid-wicket for a single. Rotates the strike cleanly under severe pressure!',
    timestamp: '2025-05-24T21:42:15Z',
  },
  {
    id: 'c_18_1',
    matchId: 'match_blr_mum_01',
    over: '18.1',
    bowlerName: 'J Bumrah',
    strikerName: 'V Kohli',
    runs: 1,
    ballType: 'run',
    isBoundary: false,
    isWicket: false,
    title: '1 run',
    description: 'Back of a length delivery angling in tightly, tapped deftly toward backward point. Quick sprint gets them through with zero hesitation.',
    timestamp: '2025-05-24T21:41:30Z',
  },
  {
    id: 'c_17_6',
    matchId: 'match_blr_mum_01',
    over: '17.6',
    bowlerName: 'H Pandya',
    strikerName: 'G Maxwell',
    runs: 6,
    ballType: 'boundary6',
    isBoundary: true,
    isWicket: false,
    title: 'SIX! Maximum over long on!',
    description: 'Slotted right into the hitting arc! Maxwell stands tall and pummels it high and deep over wide long-on for a gigantic 96-meter maximum! Electric atmosphere in the stadium!',
    timestamp: '2025-05-24T21:39:45Z',
  },
  {
    id: 'c_17_5',
    matchId: 'match_blr_mum_01',
    over: '17.5',
    bowlerName: 'H Pandya',
    strikerName: 'V Kohli',
    runs: 1,
    ballType: 'run',
    isBoundary: false,
    isWicket: false,
    title: '1 run',
    description: 'Full toss dipped on the pads, worked cleanly behind square leg for one run.',
    timestamp: '2025-05-24T21:39:10Z',
  },
  {
    id: 'c_17_4',
    matchId: 'match_blr_mum_01',
    over: '17.4',
    bowlerName: 'H Pandya',
    strikerName: 'V Kohli',
    runs: 4,
    ballType: 'boundary4',
    isBoundary: true,
    isWicket: false,
    title: 'FOUR! Trademark cover drive!',
    description: 'Pure class from King Kohli! Leans into an overpitched off-cutter and pierces the extra-cover gap with laser precision. The ball races to the boundary rope in a flash!',
    timestamp: '2025-05-24T21:38:25Z',
  },
  {
    id: 'c_17_3',
    matchId: 'match_blr_mum_01',
    over: '17.3',
    bowlerName: 'H Pandya',
    strikerName: 'V Kohli',
    runs: 2,
    ballType: 'run',
    isBoundary: false,
    isWicket: false,
    title: '2 runs',
    description: 'Steered behind point into the deep backward gap. Sensational urgency between the pair to turn a single into a brisk brace.',
    timestamp: '2025-05-24T21:37:40Z',
  },
  {
    id: 'c_15_2',
    matchId: 'match_blr_mum_01',
    over: '15.2',
    bowlerName: 'J Bumrah',
    strikerName: 'C Green',
    runs: 0,
    ballType: 'wicket',
    isBoundary: false,
    isWicket: true,
    title: 'OUT! LBW - Bumrah strikes!',
    description: 'Absolute jaffa from Bumrah! Fast, reverse-swinging yorker crashing right onto the base of the front pad. Green is caught plumb in front, umpire raises the finger instantly!',
    timestamp: '2025-05-24T21:26:00Z',
  },
];

export const mockPlayers: Record<string, Player> = {
  p_kohli: {
    id: 'p_kohli',
    name: 'Virat Kohli',
    shortName: 'V Kohli',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&q=80',
    teamId: 'team_blr',
    role: 'batsman',
    battingStyle: 'Right-hand bat',
    bowlingStyle: 'Right-arm medium',
    country: 'India',
    jerseyNumber: 18,
    careerStats: {
      matches: 252,
      runs: 8004,
      average: 38.6,
      strikeRate: 131.9,
      highestScore: 113,
      fifties: 55,
      hundreds: 8,
      wickets: 4,
      economy: 8.8,
      bestBowling: '2/25',
    },
    recentInnings: [
      { match: 'vs MUM', runs: 68, balls: 42, isOut: false, date: '2025-05-24' },
      { match: 'vs CHE', runs: 47, balls: 29, isOut: true, date: '2025-05-18' },
      { match: 'vs DEL', runs: 92, balls: 54, isOut: false, date: '2025-05-12' },
      { match: 'vs KOL', runs: 18, balls: 14, isOut: true, date: '2025-05-06' },
      { match: 'vs HYD', runs: 51, balls: 36, isOut: true, date: '2025-04-30' },
    ],
  },
  p_bumrah: {
    id: 'p_bumrah',
    name: 'Jasprit Bumrah',
    shortName: 'J Bumrah',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=256&q=80',
    teamId: 'team_mum',
    role: 'bowler',
    battingStyle: 'Right-hand bat',
    bowlingStyle: 'Right-arm fast',
    country: 'India',
    jerseyNumber: 93,
    careerStats: {
      matches: 133,
      runs: 69,
      average: 9.8,
      strikeRate: 98.4,
      highestScore: 16,
      fifties: 0,
      hundreds: 0,
      wickets: 165,
      economy: 7.3,
      bestBowling: '5/10',
    },
    recentInnings: [
      { match: 'vs BLR', runs: 28, balls: 20, isOut: false, date: '2025-05-24' },
      { match: 'vs KOL', runs: 24, balls: 24, isOut: false, date: '2025-05-22' },
      { match: 'vs CHE', runs: 18, balls: 24, isOut: false, date: '2025-05-15' },
    ],
  },
};

export const mockTournamentStandings: TournamentStanding[] = [
  {
    rank: 1,
    teamId: 'team_blr',
    teamName: 'Bengaluru Royals',
    shortName: 'BLR',
    played: 14,
    won: 10,
    lost: 4,
    noResult: 0,
    points: 20,
    nrr: '+0.892',
    recentForm: ['W', 'W', 'W', 'L', 'W'],
    group: 'A',
    qualified: true,
  },
  {
    rank: 2,
    teamId: 'team_mum',
    teamName: 'Mumbai Warriors',
    shortName: 'MUM',
    played: 14,
    won: 9,
    lost: 5,
    noResult: 0,
    points: 18,
    nrr: '+0.640',
    recentForm: ['W', 'W', 'L', 'W', 'W'],
    group: 'A',
    qualified: true,
  },
  {
    rank: 3,
    teamId: 'team_che',
    teamName: 'Chennai Kings',
    shortName: 'CHE',
    played: 14,
    won: 8,
    lost: 5,
    noResult: 1,
    points: 17,
    nrr: '+0.415',
    recentForm: ['L', 'W', 'N', 'W', 'W'],
    group: 'A',
    qualified: true,
  },
  {
    rank: 4,
    teamId: 'team_kol',
    teamName: 'Kolkata Knights',
    shortName: 'KOL',
    played: 14,
    won: 8,
    lost: 6,
    noResult: 0,
    points: 16,
    nrr: '+0.320',
    recentForm: ['W', 'L', 'W', 'L', 'W'],
    group: 'B',
    qualified: true,
  },
  {
    rank: 5,
    teamId: 'team_hyd',
    teamName: 'Hyderabad Sunbirds',
    shortName: 'HYD',
    played: 14,
    won: 7,
    lost: 7,
    noResult: 0,
    points: 14,
    nrr: '-0.105',
    recentForm: ['L', 'W', 'L', 'W', 'L'],
    group: 'B',
    qualified: false,
  },
  {
    rank: 6,
    teamId: 'team_del',
    teamName: 'Delhi Strikers',
    shortName: 'DEL',
    played: 14,
    won: 6,
    lost: 8,
    noResult: 0,
    points: 12,
    nrr: '-0.380',
    recentForm: ['L', 'L', 'W', 'L', 'W'],
    group: 'B',
    qualified: false,
  },
  {
    rank: 7,
    teamId: 'team_pun',
    teamName: 'Punjab Lions',
    shortName: 'PUN',
    played: 14,
    won: 5,
    lost: 9,
    noResult: 0,
    points: 10,
    nrr: '-0.620',
    recentForm: ['W', 'L', 'L', 'L', 'L'],
    group: 'A',
    qualified: false,
  },
  {
    rank: 8,
    teamId: 'team_raj',
    teamName: 'Rajasthan Titans',
    shortName: 'RAJ',
    played: 14,
    won: 4,
    lost: 10,
    noResult: 0,
    points: 8,
    nrr: '-0.950',
    recentForm: ['L', 'L', 'L', 'W', 'L'],
    group: 'B',
    qualified: false,
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'WICKET! Cameron Green departed',
    body: 'J. Bumrah gets Cameron Green LBW for 3 (5). BLR 115/3 (15.2 ov).',
    type: 'wicket',
    matchId: 'match_blr_mum_01',
    timestamp: '2025-05-24T21:26:00Z',
    isRead: false,
  },
  {
    id: 'notif_02',
    title: 'FIFTY! Virat Kohli 50* (34)',
    body: 'Masterclass half-century in the Semi Final chase by Virat Kohli!',
    type: 'milestone',
    matchId: 'match_blr_mum_01',
    timestamp: '2025-05-24T21:18:00Z',
    isRead: false,
  },
  {
    id: 'notif_03',
    title: 'Match 41: CHE vs DEL Toss Result',
    body: 'Chennai Kings won the toss and elected to bat first at Chepauk.',
    type: 'match_status',
    matchId: 'match_che_del_02',
    timestamp: '2025-05-24T15:00:00Z',
    isRead: true,
  },
];
